language: android
jdk:
    - oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/.gradle/caches/

env:
  global:
    MALLOC_ARENA_MAX=2

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.3
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

before_script:
    - export "JAVA_OPTS=-Xmx1024m"
    - export "JAVA7_HOME=/usr/lib/jvm/java-7-oracle"
    - export "JAVA8_HOME=/usr/lib/jvm/java-8-oracle"

script:
    - ./gradlew :app:assembleDebug testDebugUnitTest --stacktrace
